// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: aoctracker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AOCTrackerServiceClient is the client API for AOCTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AOCTrackerServiceClient interface {
	Track(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (*TrackResponse, error)
}

type aOCTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAOCTrackerServiceClient(cc grpc.ClientConnInterface) AOCTrackerServiceClient {
	return &aOCTrackerServiceClient{cc}
}

func (c *aOCTrackerServiceClient) Track(ctx context.Context, in *TrackRequest, opts ...grpc.CallOption) (*TrackResponse, error) {
	out := new(TrackResponse)
	err := c.cc.Invoke(ctx, "/aoctracker.AOCTrackerService/Track", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AOCTrackerServiceServer is the server API for AOCTrackerService service.
// All implementations should embed UnimplementedAOCTrackerServiceServer
// for forward compatibility
type AOCTrackerServiceServer interface {
	Track(context.Context, *TrackRequest) (*TrackResponse, error)
}

// UnimplementedAOCTrackerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAOCTrackerServiceServer struct {
}

func (UnimplementedAOCTrackerServiceServer) Track(context.Context, *TrackRequest) (*TrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Track not implemented")
}

// UnsafeAOCTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AOCTrackerServiceServer will
// result in compilation errors.
type UnsafeAOCTrackerServiceServer interface {
	mustEmbedUnimplementedAOCTrackerServiceServer()
}

func RegisterAOCTrackerServiceServer(s grpc.ServiceRegistrar, srv AOCTrackerServiceServer) {
	s.RegisterService(&AOCTrackerService_ServiceDesc, srv)
}

func _AOCTrackerService_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AOCTrackerServiceServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aoctracker.AOCTrackerService/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AOCTrackerServiceServer).Track(ctx, req.(*TrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AOCTrackerService_ServiceDesc is the grpc.ServiceDesc for AOCTrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AOCTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aoctracker.AOCTrackerService",
	HandlerType: (*AOCTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Track",
			Handler:    _AOCTrackerService_Track_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aoctracker.proto",
}
